[project]
name = "scrapper-function"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "google-cloud-firestore>=2.21.0",
    "playwright>=1.55.0",
]
